In [1]:
import numpy as np
import pandas as pd

Beginner Level Questions

Display the first 10 rows of the dataset.

Show the number of rows and columns (shape).

List all unique continents in the dataset.

Find the capital city of India.

Show the top 5 countries with the highest population.

Select only the columns: country, continent, population.

Which country has the minimum population?

Find all countries in Asia.

In [ ]:
df = pd.read_csv(r'Countries.csv')

In [4]:
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 64 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  194 non-null    object
 1   country_long                             194 non-null    object
 2   currency                                 194 non-null    object
 3   capital_city                             194 non-null    object
 4   region                                   194 non-null    object
 5   continent                                194 non-null    object
 6   demonym                                  194 non-null    object
 7   latitude                                 194 non-null    float64
 8   longitude                                194 non-null    float64
 9   agricultural_land                        193 non-null    float64
 10  forest_area                              194 non-null    float64
 11  land_area                                194 non-null    float64
 12  rural_land                               194 non-null    float64
 13  urban_land                               194 non-null    float64
 14  central_government_debt_pct_gdp          120 non-null    float64
 15  expense_pct_gdp                          156 non-null    float64
 16  gdp                                      193 non-null    float64
 17  inflation                                184 non-null    float64
 18  self_employed_pct                        179 non-null    float64
 19  tax_revenue_pct_gdp                      159 non-null    float64
 20  unemployment_pct                         179 non-null    float64
 21  vulnerable_employment_pct                179 non-null    float64
 22  electricity_access_pct                   194 non-null    float64
 23  alternative_nuclear_energy_pct           138 non-null    float64
 24  electricty_production_coal_pct           138 non-null    float64
 25  electricty_production_hydroelectric_pct  138 non-null    float64
 26  electricty_production_gas_pct            138 non-null    float64
 27  electricty_production_nuclear_pct        138 non-null    float64
 28  electricty_production_oil_pct            138 non-null    float64
 29  electricty_production_renewable_pct      138 non-null    float64
 30  energy_imports_pct                       138 non-null    float64
 31  fossil_energy_consumption_pct            168 non-null    float64
 32  renewable_energy_consumption_pct         192 non-null    float64
 33  co2_emissions                            191 non-null    float64
 34  methane_emissions                        191 non-null    float64
 35  nitrous_oxide_emissions                  191 non-null    float64
 36  greenhouse_other_emissions               184 non-null    float64
 37  urban_population_under_5m                194 non-null    float64
 38  health_expenditure_pct_gdp               190 non-null    float64
 39  health_expenditure_capita                190 non-null    float64
 40  hospital_beds                            192 non-null    float64
 41  hiv_incidence                            133 non-null    float64
 42  suicide_rate                             183 non-null    float64
 43  armed_forces                             174 non-null    float64
 44  internally_displaced_persons             73 non-null     float64
 45  military_expenditure_pct_gdp             163 non-null    float64
 46  birth_rate                               194 non-null    float64
 47  death_rate                               194 non-null    float64
 48  fertility_rate                           193 non-null    float64
 49  internet_pct                             194 non-null    float64
 50  life_expectancy                          191 non-null    float64
 51  net_migration                            194 non-null    int64
 52  population_female                        194 non-null    int64
 53  population_male                          194 non-null    int64
 54  population                               194 non-null    int64
 55  women_parliament_seats_pct               193 non-null    float64
 56  rural_population                         194 non-null    int64
 57  urban_population                         194 non-null    int64
 58  press                                    194 non-null    float64
 59  democracy_score                          194 non-null    float64
 60  democracy_type                           194 non-null    object
 61  median_age                               194 non-null    float64
 62  political_leader                         187 non-null    object
 63  title                                    187 non-null    object
dtypes: float64(48), int64(6), object(10)
memory usage: 97.1+ KB

In [ ]:
#Display the first 10 rows of the dataset.
df.iloc[:10]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
5,Antigua and Barbuda,Antigua and Barbuda,East Caribbean dollar,Saint John's,Caribbean,Americas,Antiguan,17.050000,-61.800000,90.0,...,93763,11.11110,70935,22828,0.00,0.00,Unknown,31.1,Gaston Browne,Prime Minister
6,Argentina,Argentine Republic,Argentine peso,Buenos Aires,South America,Americas,Argentine,-34.000000,-64.000000,1083820.0,...,46234830,44.74710,3538352,42696478,2.76,7.02,Flawed democracy,27.6,Alberto Fernández,President
7,Armenia,Republic of Armenia,Armenian dram,Yerevan,Western Asia,Asia,Armenian,40.000000,45.000000,16760.0,...,2780469,35.51400,1012841,1767628,2.70,4.79,Hybrid regime,30.8,Nikol Pashinyan,Prime Minister
8,Australia,Commonwealth of Australia,Australian dollar,Canberra,Australia and New Zealand,Oceania,Australian,-27.000000,133.000000,3557750.0,...,25978935,38.41060,3510274,22468661,4.73,9.09,Full democracy,33.3,Anthony Albanese,Prime Minister
9,Austria,Republic of Austria,Euro,Vienna,Western Europe,Europe,Austrian,47.333333,13.333333,26467.6,...,9042528,40.98360,3684288,5358240,5.10,8.29,Full democracy,39.0,Sebastian Kurz,Federal Chancellor

In [11]:
df.shape

(194, 64)

In [12]:
df.nunique()

country             194
country_long        194
currency            142
capital_city        194
region               22
                   ...
democracy_score     146
democracy_type        5
median_age          143
political_leader    187
title                17
Length: 64, dtype: int64

In [16]:
df[df['country']=='India']['capital_city']

75    New Delhi
Name: capital_city, dtype: object

In [22]:
df.sort_values(by='population',ascending=False).head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
75,India,Republic of India,Indian rupee,New Delhi,Southern Asia,Asia,Indian,20.0,77.0,1790450.0,...,1417173173,14.9446,908804812,508368361,1.71,7.23,Flawed democracy,23.9,Narendra Modi,Prime Minister
34,China,People's Republic of China,Chinese yuan,Beijing,Eastern Asia,Asia,Chinese,35.0,105.0,5285080.0,...,1412175000,24.9412,514596570,897578430,0.99,3.32,Authoritarian,34.5,Xi Jinping,General Secretary of the Communist Party
184,United States,United States of America,U.S. dollar,"Washington, D.C.",Northern America,Americas,American,38.0,-97.0,4058100.0,...,333287557,28.7037,56378923,276908634,3.04,7.96,Flawed democracy,33.9,Joe Biden,President
76,Indonesia,Republic of Indonesia,Indonesian rupiah,Jakarta,South-Eastern Asia,Asia,Indonesian,-5.0,120.0,623000.0,...,275501339,21.9130,115892393,159608946,2.13,6.39,Flawed democracy,25.6,Joko Widodo,President
129,Pakistan,Islamic Republic of Pakistan,Pakistani rupee,Islamabad,Southern Asia,Asia,Pakistani,30.0,70.0,367230.0,...,235824862,20.4678,146845783,88979079,1.71,4.17,Hybrid regime,16.5,Imran Khan,Prime Minister

In [26]:
df[['country','continent','population']]

                country continent  population
0           Afghanistan      Asia    41128771
1               Albania    Europe     2775634
2               Algeria    Africa    44903225
3               Andorra    Europe       79824
4                Angola    Africa    35588987
..                  ...       ...         ...
189             Vietnam      Asia    98186856
190  West Bank and Gaza      Asia     5043612
191               Yemen      Asia    33696614
192              Zambia    Africa    20017675
193            Zimbabwe    Africa    16320537

[194 rows x 3 columns]

Intermediate Level Questions

Calculate the mean population of all countries.

Find the country with the highest GDP.

Sort countries by life_expectancy in descending order.

Group by continent and find the average population.

Find all countries with urban_population > rural_population.

Which continent has the maximum total forest_area?

Count how many countries are classified as "Full democracy".

For each continent, find the median democracy_score.

Which country has the highest electricity_access_pct?

List all countries where internet_pct > 90.

In [37]:
df['population'].mean()

np.float64(40788877.788659796)

In [33]:
df[df['gdp']==df['gdp'].max()]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
184,United States,United States of America,U.S. dollar,"Washington, D.C.",Northern America,Americas,American,38.0,-97.0,4058100.0,...,333287557,28.7037,56378923,276908634,3.04,7.96,Flawed democracy,33.9,Joe Biden,President

In [39]:
df.sort_values(by='life_expectancy',ascending=False).head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
97,Liechtenstein,Principality of Liechtenstein,Swiss franc,Vaduz,Western Europe,Europe,Liechtensteiner,47.266667,9.533333,53.2,...,39327,28.00000,33610,5717,3.82,0.00,Unknown,39.9,Hereditary Prince Alois,Regent
83,Japan,Japan,Japanese yen,Tokyo,Eastern Asia,Asia,Japanese,36.000000,138.000000,43720.0,...,125124989,9.91379,10066305,115058684,2.66,7.99,Flawed democracy,44.7,Yoshihide Suga,Prime Minister
88,Korea,Republic of Korea,Korean won,Seoul,Eastern Asia,Asia,South Korean,37.000000,127.500000,16210.0,...,51628117,18.64410,9588890,42039227,3.14,8.00,Flawed democracy,39.9,Yoon Suk-yeol,President
165,Switzerland,Switzerland,Swiss franc,Bern,Western Europe,Europe,Swiss,47.000000,8.000000,15042.1,...,8769741,41.50000,2272064,6497677,7.43,9.03,Full democracy,38.1,Simonetta Sommaruga,President
8,Australia,Commonwealth of Australia,Australian dollar,Canberra,Australia and New Zealand,Oceania,Australian,-27.000000,133.000000,3557750.0,...,25978935,38.41060,3510274,22468661,4.73,9.09,Full democracy,33.3,Anthony Albanese,Prime Minister

In [41]:
df.groupby('continent')['population'].mean()

continent
Africa      2.638538e+07
Americas    2.936354e+07
Asia        9.953398e+07
Europe      1.678467e+07
Oceania     3.134620e+06
Name: population, dtype: float64

In [45]:
df[df['urban_population'] >df['rural_population']]['country']

1                 Albania
2                 Algeria
3                 Andorra
4                  Angola
6               Argentina
              ...
184         United States
185               Uruguay
186            Uzbekistan
188             Venezuela
190    West Bank and Gaza
Name: country, Length: 129, dtype: object

In [47]:
df[df['forest_area'] ==df['forest_area'].max()]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
140,Russia,Russian Federation,Russian ruble,Moscow,Eastern Europe,Europe,Russian,60.0,100.0,2154940.0,...,143555736,16.2222,35708054,107847682,1.55,2.94,Authoritarian,35.0,Vladimir Putin,President

In [52]:
df.groupby('continent')['forest_area'].sum().idxmax()

'Americas'

In [57]:
df[df['democracy_type']=='Full democracy']['country'].count()

np.int64(20)

In [62]:
df.groupby('continent',as_index=False)['democracy_score'].median()

  continent  democracy_score
0    Africa            3.735
1  Americas            6.190
2      Asia            3.930
3    Europe            7.500
4   Oceania            0.000

In [65]:
df[df['electricity_access_pct'] ==df['electricity_access_pct'].max()].head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.00,20.0,11655.5,...,2775634,35.7143,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.50,1.5,187.2,...,79824,46.4286,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
5,Antigua and Barbuda,Antigua and Barbuda,East Caribbean dollar,Saint John's,Caribbean,Americas,Antiguan,17.05,-61.8,90.0,...,93763,11.1111,70935,22828,0.00,0.00,Unknown,31.1,Gaston Browne,Prime Minister
6,Argentina,Argentine Republic,Argentine peso,Buenos Aires,South America,Americas,Argentine,-34.00,-64.0,1083820.0,...,46234830,44.7471,3538352,42696478,2.76,7.02,Flawed democracy,27.6,Alberto Fernández,President
7,Armenia,Republic of Armenia,Armenian dram,Yerevan,Western Asia,Asia,Armenian,40.00,45.0,16760.0,...,2780469,35.5140,1012841,1767628,2.70,4.79,Hybrid regime,30.8,Nikol Pashinyan,Prime Minister

In [74]:
df.loc[df['internet_pct'] >90,['country','internet_pct']].head()

                country  internet_pct
3               Andorra       93.8975
5   Antigua and Barbuda       95.6634
8             Australia       96.2400
9               Austria       92.5292
11              Bahrain      100.0000

Advanced Level Questions

Create a new column GDP_per_capita = gdp / population.

Find the top 10 countries with highest GDP_per_capita.

For each continent, find the country with the highest GDP.

Compare average life_expectancy of democracies vs authoritarian regimes.

Find the correlation between health_expenditure_pct_gdp and life_expectancy.

Create a new column population_density = population / land_area. Show the top 5 densest countries.

Group by democracy_type and find the average press freedom score.

Find the top 5 countries with the largest difference between rural_population and urban_population.

For each continent, find the total CO2 emissions.

Plot a bar chart of GDP by continent (use Matplotlib).

In [81]:
df['GDP_per_capita'] = df['gdp'] / df['population']
df['GDP_per_capita'].tail()

189    4163.510440
190    3789.327966
191     641.197955
192    1487.910059
193    1266.998751
Name: GDP_per_capita, dtype: float64

In [82]:
df.sort_values(by='GDP_per_capita',ascending=False)

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title,GDP_per_capita
112,Monaco,Principality of Monaco,Euro,Monaco,Western Europe,Europe,Monegasque,43.733333,7.400000,NaN,...,33.3333,0,36469,0.00,0.00,Unknown,50.5,Albert II,Sovereign Prince,235711.426143
97,Liechtenstein,Principality of Liechtenstein,Swiss franc,Vaduz,Western Europe,Europe,Liechtensteiner,47.266667,9.533333,53.20,...,28.0000,33610,5717,3.82,0.00,Unknown,39.9,Hereditary Prince Alois,Regent,182735.270933
99,Luxembourg,Grand Duchy of Luxembourg,Euro,Luxembourg,Western Europe,Europe,Luxembourger,49.750000,6.166667,1321.36,...,33.3333,52836,597938,4.99,8.81,Full democracy,35.0,Xavier Bettel,Prime Minister,126426.071109
127,Norway,Kingdom of Norway,Norwegian krone,Oslo,Northern Europe,Europe,Norwegian,62.000000,10.000000,9859.62,...,44.9704,891476,4565651,10.00,9.87,Full democracy,35.6,Erna Solberg,Prime Minister,106148.711584
79,Ireland,Ireland,Euro,Dublin,Northern Europe,Europe,Irish,53.000000,-8.000000,45120.00,...,23.1250,1822006,3264982,5.21,9.15,Full democracy,33.9,Leo Varadkar,Taoiseach,104038.971588
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,Sierra Leone,Republic of Sierra Leone,Sierra Leonean leone,Freetown,Western Africa,Africa,Sierra Leonean,8.500000,-11.500000,39490.00,...,12.3288,4833746,3771972,2.58,4.66,Hybrid regime,15.1,Julius Maada Bio,President,461.360691
31,Central African Republic,Central African Republic,Central African CFA franc,Bangui,Middle Africa,Africa,Central African,7.000000,21.000000,50800.00,...,12.8571,3173417,2405727,1.65,1.52,Authoritarian,10.8,Faustin-Archange Touadéra,President,427.058344
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.00,...,27.0161,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President,354.571742
26,Burundi,Republic of Burundi,Burundi franc,Bujumbura,Eastern Africa,Africa,Burundian,-3.500000,30.000000,20330.00,...,38.2114,11031286,1858290,1.48,2.33,Authoritarian,11.9,Pierre Nkurunziza,President,238.441513
44,Dem. People's Rep. Korea,Democratic People's Republic of Korea,Democratic People's Republic of Korean won,Pyongyang,Eastern Asia,Asia,North Korean,40.000000,127.000000,25900.00,...,17.6128,9667582,16401834,0.94,1.08,Authoritarian,31.9,Kim Jong-un,Chairman of the Workers Party of Korea,NaN