In [2]:
import pandas as pd
import numpy as np

In [3]:
df =pd.read_csv(r'./datasets/movies.csv')

In [4]:
df.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB

In [6]:
df.shape

(1629, 18)

In [7]:
df.isna()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
4,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
1625,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
1626,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True
1627,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False
1628,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False

In [8]:
df.isna().sum()

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [9]:
df.isna().any()

title_x             False
imdb_id             False
poster_path          True
wiki_link           False
title_y             False
original_title      False
is_adult            False
year_of_release     False
runtime             False
genres              False
imdb_rating         False
imdb_votes          False
story                True
summary             False
tagline              True
actors               True
wins_nominations     True
release_date         True
dtype: bool

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.head(1)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)

In [12]:
df[['actors','title_y','release_date']].head()

,actors,title_y,release_date
0,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,Uri: The Surgical Strike,11 January 2019 (USA)
1,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,Battalion 609,11 January 2019 (India)
2,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,The Accidental Prime Minister,11 January 2019 (USA)
3,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,Why Cheat India,18 January 2019 (USA)
4,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,Evening Shadows,11 January 2019 (India)

In [13]:
type(df['actors'])

pandas.core.series.Series

In [14]:
df =df.fillna(method='ffill')

C:\Users\karli\AppData\Local\Temp\ipykernel_19756\3187907699.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df =df.fillna(method='ffill')

In [15]:
df.dropna(inplace=True)

In [16]:
df.isna().any()

title_x             False
imdb_id             False
poster_path         False
wiki_link           False
title_y             False
original_title      False
is_adult            False
year_of_release     False
runtime             False
genres              False
imdb_rating         False
imdb_votes          False
story               False
summary             False
tagline             False
actors              False
wins_nominations    False
release_date        False
dtype: bool

In [17]:
df.isna().sum()

title_x             0
imdb_id             0
poster_path         0
wiki_link           0
title_y             0
original_title      0
is_adult            0
year_of_release     0
runtime             0
genres              0
imdb_rating         0
imdb_votes          0
story               0
summary             0
tagline             0
actors              0
wins_nominations    0
release_date        0
dtype: int64

movies with higher rating than 8 and vote 10000

In [18]:
df.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
7,Bombairiya,tt4971258,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bombairiya,Bombairiya,Bombairiya,0,2019,104,Comedy|Crime|Drama,4.3,295,It follows the story of Meghna who gets embro...,It follows the story of Meghna who gets embro...,They didn't mean to change the world.,Radhika Apte|Akshay Oberoi|Siddhanth Kapoor|Ra...,3 wins & 5 nominations,18 January 2019 (India)
8,Manikarnika: The Queen of Jhansi,tt6903440,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Manikarnika:_The...,Manikarnika: The Queen of Jhansi,Manikarnika: The Queen of Jhansi,0,2019,148,Action|Biography|Drama,6.5,7361,Manikarnika born in Varanasi when Dixt a minis...,Story of Rani Lakshmibai one of the leading f...,They didn't mean to change the world.,Kangana Ranaut|Rimi Sen|Atul Kulkarni|Nalneesh...,3 wins & 5 nominations,25 January 2019 (USA)
9,Thackeray (film),tt7777196,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Thackeray_(film),Thackeray,Thackeray,0,2019,120,Biography|Drama,5.1,2301,Balasaheb Thackrey works as a cartoonist for a...,Biographical account of Shiv Sena Supremo Bal...,They didn't mean to change the world.,Nawazuddin Siddiqui|Amrita Rao|Abdul Quadir Am...,3 wins & 5 nominations,25 January 2019 (India)
10,Amavas,tt8396186,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Amavas,Amavas,Amavas,0,2019,134,Horror|Thriller,2.8,235,Far away from the bustle of the city a young ...,The lives of a couple turn into a nightmare a...,They didn't mean to change the world.,Ali Asgar|Vivan Bhatena|Nargis Fakhri|Sachiin ...,3 wins & 5 nominations,8 February 2019 (India)
11,Gully Boy,tt2395469,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gully_Boy,Gully Boy,Gully Boy,0,2019,153,Drama|Music,8.2,22440,"Gully Boy is a film about a 22-year-old boy ""M...",A coming-of-age story based on the lives of st...,Apna Time Aayega!,Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...,6 wins & 3 nominations,14 February 2019 (USA)

In [19]:
r8_v_10k =df[(df['imdb_rating']>8) & (df['imdb_votes']>100000)]

In [20]:
r8_v_10k.shape

(5, 18)

In [21]:
#action movies with higher rating than 7.5

In [22]:
df.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
7,Bombairiya,tt4971258,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bombairiya,Bombairiya,Bombairiya,0,2019,104,Comedy|Crime|Drama,4.3,295,It follows the story of Meghna who gets embro...,It follows the story of Meghna who gets embro...,They didn't mean to change the world.,Radhika Apte|Akshay Oberoi|Siddhanth Kapoor|Ra...,3 wins & 5 nominations,18 January 2019 (India)
8,Manikarnika: The Queen of Jhansi,tt6903440,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Manikarnika:_The...,Manikarnika: The Queen of Jhansi,Manikarnika: The Queen of Jhansi,0,2019,148,Action|Biography|Drama,6.5,7361,Manikarnika born in Varanasi when Dixt a minis...,Story of Rani Lakshmibai one of the leading f...,They didn't mean to change the world.,Kangana Ranaut|Rimi Sen|Atul Kulkarni|Nalneesh...,3 wins & 5 nominations,25 January 2019 (USA)
9,Thackeray (film),tt7777196,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Thackeray_(film),Thackeray,Thackeray,0,2019,120,Biography|Drama,5.1,2301,Balasaheb Thackrey works as a cartoonist for a...,Biographical account of Shiv Sena Supremo Bal...,They didn't mean to change the world.,Nawazuddin Siddiqui|Amrita Rao|Abdul Quadir Am...,3 wins & 5 nominations,25 January 2019 (India)
10,Amavas,tt8396186,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Amavas,Amavas,Amavas,0,2019,134,Horror|Thriller,2.8,235,Far away from the bustle of the city a young ...,The lives of a couple turn into a nightmare a...,They didn't mean to change the world.,Ali Asgar|Vivan Bhatena|Nargis Fakhri|Sachiin ...,3 wins & 5 nominations,8 February 2019 (India)
11,Gully Boy,tt2395469,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gully_Boy,Gully Boy,Gully Boy,0,2019,153,Drama|Music,8.2,22440,"Gully Boy is a film about a 22-year-old boy ""M...",A coming-of-age story based on the lives of st...,Apna Time Aayega!,Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...,6 wins & 3 nominations,14 February 2019 (USA)

In [23]:
def s(a):
    genes= a.split('|')
    return 'Action' in genes

In [24]:
act =df['genres'].str.split('|').apply(lambda x:'Action' in x)

In [25]:
act2 = df['genres'].apply(s)

In [26]:
rate_75 =df['imdb_rating']>7.5

In [27]:
rate_75.head(1)

7    False
Name: imdb_rating, dtype: bool

In [28]:
df[act & rate_75].shape

(32, 18)

In [29]:
df[act2& rate_75].shape

(32, 18)

In [30]:
df[act2& rate_75].head(1)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
41,Family of Thakurganj,tt8897986,https://upload.wikimedia.org/wikipedia/en/9/99...,https://en.wikipedia.org/wiki/Family_of_Thakur...,Family of Thakurganj,Family of Thakurganj,0,2019,127,Action|Drama,9.4,895,The film is based on small town of North India...,The film is based on small town of North India...,Inspired by the Life of Anand Kumar & His Stud...,Jimmy Sheirgill|Mahie Gill|Nandish Singh|Prana...,1 win,19 July 2019 (India)


adding new column

In [31]:
df['Country'] = 'India'

In [32]:
df['Country']

7       India
8       India
9       India
10      India
11      India
        ...
1624    India
1625    India
1626    India
1627    India
1628    India
Name: Country, Length: 1622, dtype: object

In [33]:
def ac(x):
    ac = x.split('wins')
    return ac[0]

In [34]:
win =df['wins_nominations'].apply(ac)

In [35]:
def act(x):
    acc = x.split('|')
    return acc[0]

In [36]:
df['actors'].str.split('|').apply(lambda x : x[0]).head()

7            Radhika Apte
8          Kangana Ranaut
9     Nawazuddin Siddiqui
10              Ali Asgar
11          Ranveer Singh
Name: actors, dtype: object

In [37]:
df['actors'].apply(act).tail()

1624       Ajay Devgn
1625    Ameesha Patel
1626      Vijay Arora
1627     Gippy Grewal
1628       Fawad Khan
Name: actors, dtype: object

In [38]:
def d(s):
    ss = s.split("& ")
    return ss

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1622 entries, 7 to 1628
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1622 non-null   object
 1   imdb_id           1622 non-null   object
 2   poster_path       1622 non-null   object
 3   wiki_link         1622 non-null   object
 4   title_y           1622 non-null   object
 5   original_title    1622 non-null   object
 6   is_adult          1622 non-null   int64
 7   year_of_release   1622 non-null   int64
 8   runtime           1622 non-null   object
 9   genres            1622 non-null   object
 10  imdb_rating       1622 non-null   float64
 11  imdb_votes        1622 non-null   int64
 12  story             1622 non-null   object
 13  summary           1622 non-null   object
 14  tagline           1622 non-null   object
 15  actors            1622 non-null   object
 16  wins_nominations  1622 non-null   object
 17  release_date      1622 non-null   object
 18  Country           1622 non-null   object
dtypes: float64(1), int64(3), object(15)
memory usage: 253.4+ KB

In [40]:
df['actors'].astype('str')

7       Radhika Apte|Akshay Oberoi|Siddhanth Kapoor|Ra...
8       Kangana Ranaut|Rimi Sen|Atul Kulkarni|Nalneesh...
9       Nawazuddin Siddiqui|Amrita Rao|Abdul Quadir Am...
10      Ali Asgar|Vivan Bhatena|Nargis Fakhri|Sachiin ...
11      Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...
                              ...
1624    Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...
1625    Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...
1626    Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...
1627                            Gippy Grewal|Zareen Khan|
1628                                          Fawad Khan|
Name: actors, Length: 1622, dtype: object